# Directorios
# dir_logs      Ubicación de los logs. Lo que se descargue se guardará aquí y de aquí se lee para procesar.
# dir_save      Ubicación de los ficheros de salida (HTML y Excel)
# dir_logs: "data/21 marzo"
dir_logs: "C:/Users/jose.espinosa/Documents/Data"
dir_save: "output/test"
# dir_save: "output/grandes"
# dir_save: "output/Madrid"
# dir_save: "output/Cantabria"
# dir_save: "data/shiny"
# dir_save: "C:/Users/jose.espinosa/ADIF/Elcano - _Análisis Calidad Datos MSE y MIE/1. anticipación y ocupación"
# dir_save: "C:/Users/jose.espinosa/ADIF/Elcano - _Análisis Calidad Datos MSE y MIE/2. aproximaciones con dos vías de ctc"
# dir_save: "C:/Users/jose.espinosa/ADIF/Elcano - _Análisis Calidad Datos MSE y MIE/PRE"


# Descargar logs
# descargar     true:  activa la descarga de los últimos segundos
#               false: no descarga
# Descarga los logs de los últimos segundos (máximo 2 días). (1 hora: 3600, 1 día: 86400, 2 día: 172800)
# pro           true: utiliza xsiv PRO y lo guarda en la carpeta standard
#               false: utiliza xsiv PRE y lo guarda en la carpeta PRE
# source        xsiv: utiliza mensajería mse xsiv
#               mie_mse: utiliza mensajería mie
# # descargar: false
# # segundos: 129600
# # segundos: 172800
pro: true
# pro: false
source: xsiv
# source: mie_mse

# Procesar
# Qué se quiere procesar. Genera HTML y Excel. Se pueden elegir los 2.
# días      Fechas elegidas (todos los días en una misma representación) 
# semanas   Fechas elegidas (cada semana en una representación) 
process:
    - "días"
    # - "semanas"
    # - "AproximacionesIncorrectas"
    # - "EntreEstaciones"

# Fechas a procesar
# Selecciona de los logs las fechas a procesar.
# Si elegimos procesar semanas completas hay que definir
# cuándo empieza la semana: (0:lunes, 1:martes, ..., 4:viernes)
# y se procesarán únicamente semanas completas, es decir, si la fecha de inicio
# es un lunes pero elegimos que el inicio de semana sea un viernes se procesará
# únicamente a partir del primer viernes después de la fecha elegida.
# start_date: "2024-3-19 00:00:00"
# end_date: "2024-3-22 00:00:00"

# start_date: "2024-07-11"
# end_date: "2024-07-13"

start_date: "2025-03-10 00:00:00"
end_date: "2025-03-11 00:00:00"
start_of_week: 4

# Estaciones que queremos
estaciones:
    # - "35608"

    # MADRID
    # - "10000"  # MADRID-PRINCIPE PIO
    # - "10100"  # PINAR DE LAS ROZAS
    # - "10400"  # ÁVILA
    # - "10200"  # VILLALBA DE GUADARRAMA
    # - "10203"  # EL ESCORIAL
    # - "12006"  # CERCEDILLA
    # - "17000"  # MADRID-CHAMARTÍN
    # - "17001"  # FUENCARRAL
    # - "17005"  # COLMENAR VIEJO
    # - "17009"  # UNIVERSIDAD-CANTOBLANCO
    # - "18000"  # MADRID-ATOCHA CERCANIAS
    # - "18001"  # RECOLETOS
    # - "18002"  # MADRID-NUEVOS MINISTERIOS
    # - "18004"  # DELICIAS
    # - "18101"  # SOL
    # - "19003"  # ALCOBENDAS SAN SEBASTIAN DE LOS REYES
    # - "35002"  # FUENLABRADA
    # - "35012"  # HUMANES
    # - "35607"  # MOSTOLES-EL SOTO
    # - "37001"  # VILLAVERDE ALTO
    # - "37012"  # PARLA
    # - "60100"  # VILLAVERDE BAJO
    # - "60200"  # ARANJUEZ
    # - "70001"  # VALLECAS IND.
    # - "70103"  # ALCALA DE HENARES
    # - "70200"  # GUADALAJARA
    # - "97100"  # PITIS
    # - "98001"  # HORTALEZA
    # - "98305"  # AEROPUERTO T-4
    # - "B6002"  # BIF. PLANETARIO
    # - "B1803"  # BIF. STA. CATALINA

    # - "60102"  # GETAFE INDUSTRIAL
    # - "60104"  # VALDEMORO
    # - "60103"  # PINTO
    # - "18003"  # MÉNDEZ ÁLVARO (C1/C10)
    # - "35701"  # MÉNDEZ ÁLVARO (C5)
    # - "10101"  # LAS MATAS

    # # GRANDES
    # # - "03216"  # valencia_joaquin_sorolla
    # - "04040"  # zaragoza_delicias
    # # - "10000"  # madrid_principe_pio
    # # - "13200"  # bilbao
    # # - "14223"  # santander
    # # - "15211"  # oviedo
    # # - "15410"  # gijón
    - "17000"  # madrid_chamartin
    # # - "18000"  # madrid_atocha_cercanias
    # # - "18001"  # madrid_recoletos
    # # - "18002"  # madrid_nuevos_ministerios
    # - "50500"  # córdoba
    # - "51003"  # sevilla_santa_justa
    - "54413"  # málaga_maría_zambrano
    # - "60000"  # madrid_puerta_atocha
    # # - "65000"  # valencia_estacio_nord
    # # - "71600"  # san_vicenç_calders
    # - "71801"  # barcelona_sants
    # # - "72305"  # l'hospitalet
    # # - "79400"  # barcelona_francia
    # - "61200" # murcia
    # - "60911" # alicante
    # - "03208" # cuenca_fernando_zobel

    # # CANTABRIA
    # - "05602"
    # - "05603"
    # - "05604"
    # - "05605"
    # - "05609"
    # - "05611"
    # - "05613"
    # - "05615"
    # - "05617"
    # - "05619"
    # - "05620"
    # - "05621" # TORRELAVEGA CENTRO
    # - "05622"
    # - "05623"
    # - "05625"
    # - "05627"
    # - "05629"
    # - "05631"
    # - "05633"
    # - "05635"
    # - "05637"
    # - "05641"
    # - "05643"
    # - "05644"
    # - "05645"
    # - "05647"
    # - "05649"
    # - "05650"
    # - "05651"
    # - "05652"
    # - "05655"
    # - "05657"
    # - "05658"
    # - "05659"
    # - "05661"
    # - "05663"
    # - "05665"
    # - "05667"
    # - "05669"
    # - "05671"
    # - "14223"

    # # ASTURIAS
    # - "05102"
    # - "05103"
    # - "05104"
    # - "05105"
    # - "05106"
    # - "05107"
    # - "05108"
    # - "05109"
    # - "05111"
    # - "05113"
    # - "05115"
    # - "05117"
    # - "05119"
    # - "05121"
    # - "05123"
    # - "05125"
    # - "05127"
    # - "05129"
    # - "05131"
    # - "05133"
    # - "05135"
    # - "05137"
    # - "05139"
    # - "05141"
    # - "05143"
    # - "05145"
    # - "05147"
    # - "05149"
    # - "05151"
    # - "05153"
    # - "05155"
    # - "05156"
    # - "05157"
    # - "05159"
    # - "05161"
    # - "05163"
    # - "05165"
    # - "05167"
    # - "05169"
    # - "05171"
    # - "05173"
    # - "05175"
    # - "05177"
    # - "05179"
    # - "05181"
    # - "05183"
    # - "05185"
    # - "05187"
    # - "05189"
    # - "05191"
    # - "05193"
    # - "05197"
    # - "05199"
    # - "05203"
    # - "05204"
    # - "05207"
    # - "05208"
    # - "05209"
    # - "05210"
    # - "05211"
    # - "05213"
    # - "05215"
    # - "05216"
    # - "05217"
    # - "05218"
    # - "05219"
    # - "05220"
    # - "05221"
    # - "05223"
    # - "05224"
    # - "05225"
    # - "05227"
    # - "05229"
    # - "05231"
    # - "05232"
    # - "05233"
    # - "05235"
    # - "05237"
    # - "05239"
    # - "05241"
    # - "05243"
    # - "05244"
    # - "05245"
    # - "05247"
    # - "05249"
    # - "05251"
    # - "05253"
    # - "05255"
    # - "05257"
    # - "05259"
    # - "05261"
    # - "05263"
    # - "05265"
    # - "05267"
    # - "05269"
    # - "05271"
    # - "05273"
    # - "05275"
    # - "05277"
    # - "05279"
    # - "05281"
    # - "05283"
    # - "05285"
    # - "05287"
    # - "05289"
    # - "05291"
    # - "05293"
    # - "05295"
    # - "05297"
    # - "05299"
    # - "05300"
    # - "05301"
    # - "05302"
    # - "05303"
    # - "05304"
    # - "05305"
    # - "05306"
    # - "05308"
    # - "05311"
    # - "05313"
    # - "05315"
    # - "05316"
    # - "05317"
    # - "05319"
    # - "05320"
    # - "05321"
    # - "05323"
    # - "05325"
    # - "05329"
    # - "05353"
    # - "05361"
    # - "05367"
    # - "05369"
    # - "05371"
    # - "05373"
    # - "05375"
    # - "05376"
    # - "05377"
    # - "05379"
    # - "05380"
    # - "05381"
    # - "05382"
    # - "05383"
    # - "05384"
    # - "05385"
    # - "05387"
    # - "05389"
    # - "05403"
    # - "05405"
    # - "05407"
    # - "05409"
    # - "05410"
    # - "05411"
    # - "05412"
    # - "05413"
    # - "05415"
    # - "05416"
    # - "05417"
    # - "05420"
    # - "05421"
    # - "05425"
    # - "05429"
    # - "05431"
    # - "05432"
    # - "05433"
    # - "05435"
    # - "05436"
    # - "05437"
    # - "05439"
    # - "05441"
    # - "05443"
    # - "05446"
    # - "05504"
    # - "05505"
    # - "05507"
    # - "05508"
    # - "05509"
    # - "05511"
    # - "05513"
    # - "05515"
    # - "05517"
    # - "05519"
    # - "05521"
    # - "05522"
    # - "05523"
    # - "05525"
    # - "05527"
    # - "05529"
    # - "05531"
    # - "05533"
    # - "05534"
    # - "05535"
    # - "05537"
    # - "05539"
    # - "05541"
    # - "05542"
    # - "05543"
    # - "05545"
    # - "05547"
    # - "05549"
    # - "05551"
    # - "05553"
    # - "05555"
    # - "05557"
    # - "05559"
    # - "05561"
    # - "05563"
    # - "05565"
    # - "05567"
    # - "05569"
    # - "05571"
    # - "15205"
    # - "15206"
    # - "15211"
    # - "15217"
    # - "15400"
    # - "15410"
    # - "16403"
    # - "21010"
    # - "A1703"
    # - "A1983"
    # - "A1984"
    # - "A1985"
    # - "A1986"
    # - "C1501"
    # - "C5259"
    # - "C526"

    # # BCN
    # - "71801"
    # - "79009"
    # - "71802"
    # - "B7181"
    # - "78402"
    # - "78501"
    # - "78502"
    # - "78503"
    # - "78504"
    # - "78505"
    # - "78506"
    # - "78706"
    # - "78707"
    # - "78708"
    # - "78500"
    # - "78605"
    # - "78606"
    # - "78607"
    # - "78609"
    # - "78600"
    # - "78403"
    # - "78703"
    # - "78704"
    # - "78705"
    # - "78709"
    # - "78604"
    # - "78404"
    # - "78405"
    # - "78406"
    # - "78407"
    # - "78408"
    # - "78610"
    # - "78700"
    # - "78701"
    # - "78702"
    # - "78710"
    # - "79502"
    # - "79600"
    # - "79403"
    # - "79404"
    # - "79606"
    # - "77107"
    # - "79101"
    # - "77105"
    # - "79601"
    # - "79603"
    # - "79407"
    # - "79408"
    # - "79409"
    # - "77103"
    # - "79303"
    # - "79304"
    # - "79007"
    # - "79100"
    # - "79109"
    # - "79206"
    # - "79205"
    # - "79300"
    # - "77006"
    # - "77100"
    # - "77306"
    # - "77307"
    # - "79102"
    # - "79011"
    # - "77102"
    # - "79005"
    # - "77110"
    # - "79605"
    # - "77002"
    # - "77003"
    # - "77004"
    # - "79107"
    # - "79200"
    # - "79607"
    # - "79405"
    # - "79406"
    # - "79006"
    # - "79500"
    # - "79501"
    # - "77005"
    # - "79604"
    # - "79608"
    # - "77304"
    # - "77305"
    # - "77309"
    # - "77303"
    # - "77200"
    # - "77301"
    # - "79301"
    # - "79302"
    # - "79319"
    # - "79105"
    # - "79106"
    # - "79305"
    # - "79320"
    # - "79103"
    # - "79104"
    # - "79306"
    # - "77104"
    # - "79602"
    # - "77113"
    # - "77114"
    # - "77111"
    # - "77112"
    # - "77109"
    # - "79308"
    # - "79410"
    # - "79412"
    # - "73101"
    # - "73110"
    # - "71704"
    # - "71705"
    # - "71601"
    # - "71602"
    # - "71603"
    # - "71604"
    # - "71703"
    # - "71706"
    # - "71709"
    # - "73100"
    # - "65411"
    # - "72100"
    # - "72101"
    # - "71600"
    # - "76001"
    # - "71701"
    # - "71502"
    # - "71503"
    # - "71500"
    # - "65412"
    # - "76002"
    # - "76003"
    # - "76004"
    # - "71700"
    # - "78802"
    # - "78806"
    # - "78804"
    # - "78805"
    # - "71708"
    # - "71901"
    # - "79400"
    # - "72302"
    # - "72303"
    # - "72503"
    # - "72210"
    # - "72211"
    # - "72203"
    # - "71707"
    # - "72400"
    # - "72201"
    # - "72205"
    # - "72305"
    # - "72202"
    # - "78800"
    # - "72208"
    # - "72209"
    # - "72300"
    # - "72301"
    # - "72506"
    # - "73102"
    # - "71908"
    # - "72504"
    # - "72501"
    # - "72206"
    # - "72207"
    # - "72502"
    # - "72204"
    # - "71401"
    # - "71403"
    # - "72212"
    # - "78801"
    # - "79004"
    # - "81211"
    # - "81210"
    # - "70502"
    # - "70503"
    # - "78304"
    # - "78102"
    # - "70500"
    # - "71211"
    # - "78302"
    # - "81209"
    # - "81208"
    # - "70600"
    # - "70705"
    # - "67100"
    # - "67021"
    # - "70504"
    # - "70505"
    # - "73021"
    # - "70800"
    # - "70801"
    # - "71204"
    # - "71203"
    # - "70803"
    # - "78902"
    # - "81205"
    # - "67002"
    # - "71102"
    # - "71302"
    # - "71301"
    # - "70601"
    # - "67011"
    # - "70703"
    # - "70704"
    # - "71202"
    # - "71206"
    # - "71208"
    # - "67017"
    # - "67016"
    # - "67015"
    # - "67014"
    # - "71210"
    # - "71103"
    # - "78201"
    # - "70706"
    # - "70707"
    # - "74201"
    # - "74200"
    # - "73002"
    # - "73007"
    # - "71101"
    # - "71200"
    # - "71109"
    # - "71108"
    # - "73004"
    # - "73003"
    # - "71307"
    # - "78400"
    # - "81207"
    # - "71303"
    # - "78202"
    # - "67004"
    # - "71100"
    # - "78301"
    # - "71300"
    # - "70607"
    # - "70604"
    # - "70605"
    # - "70606"
    # - "70608"
    # - "67020"
    # - "67019"
    # - "67018"
    # - "71207"
    # - "70602"
    # - "70603"
    # - "73010"
    # - "71305"
    # - "71304"
    # - "73001"
    # - "71104"
    # - "71105"
    # - "78305"
    # - "71209"
    # - "70700"
    # - "70701"
    # - "70702"
    # - "70804"
    # - "73022"
    # - "73006"
    # - "81204"
    # - "71306"
    # - "71201"
    # - "78004"
    # - "78203"
    # - "78300"
    # - "70404"
    # - "78303"
    # - "78200"
    # - "78204"
    # - "73009"
    # - "78005"
    # - "67013"
    # - "73005"
    # - "78007"
    # - "04040"
    # - "70805"
    # - "70806"
    # - "78100"
    # - "67007"
    # - "67010"
    # - "67009"
    # - "73008"
    # - "71205"

    # # ZGZ AV
    # - "04028"
    # - "04020"
    # - "04005"
    # - "04103"
    # - "04013"
    # - "04018"
    # - "04052"
    # - "04101"
    # - "04009"
    # - "71801"
    # - "04048"
    # - "70600"
    # - "04102"
    # - "04108"
    # - "79300"
    # - "04007"
    # - "04030"
    # - "04011"
    # - "78400"
    # - "04302"
    # - "04015"
    # - "B4300"
    # - "04055"
    # - "04105"
    # - "04001"
    # - "04104"
    # - "04028"
    # - "04110"
    # - "04303"
    # - "04100"
    # - "04109"
    # - "04107"
    # - "04304"
    # - "04040"
    # - "04106"
    # - "04307"